### ISSUE TITLE
demo section is not work

### ISSUE THREAD

**Issue by thiatrat** [maxkueng/somascrobbler-api#3]
this can hardly be called serious bug, but demo section is not work.

I suppose that should appear in the demo section title tracks and stations.

here

![demo](http://pp.screenshotlink.ru/v1658/10d/2MIvgyfVr0Y.png)

but it always empty. I waited a lot of time, but there is nothing appeared.

**Comment by maxkueng** [comment]
This is fixed in version 1.x. The demo now connects to the server based on `window.location` and no longer depends on server settings. Note that if you upgrade somascrobbler-api to 1.x you'll also have to upgrade [somascrobbler](https://github.com/maxkueng/somascrobbler) to >1.0.0.
