### ISSUE TITLE
Upgrade: api.somascrobbler.com

### ISSUE THREAD

**Issue by maxkueng** [maxkueng/somascrobbler-api#4]
@gyaresu @lantrix @ymdk @moneypenny @thiatrat

First of all sorry for mentioning everybody. If this doesn't interest you please ignore. I'm trying to reach everybody who's using  the public SomaScrobber API in order to avoid any issues.

On April 1st 2015 00:00:00 UTC the public instance of SomaScrobbler API at http://api.somascrobbler.com/ will be upgraded to the latest version. This upgrade includes Socket.io 1.3.5 which is incompatible with version 0.9.16 used in the previous version.

If you're using your own client library please upgrade before April 1st. An instance of the new SomaScrobbler API is available at http://api2.somascrobbler.com/ that can be used already. After April 1st the new API will be available under both "api" and "api2" subdomains. Ideally though you'd switch back to the the original subdomain at some point.

If you're using [SomaScrobbler](https://github.com/maxkueng/somascrobbler) please upgrade to version >1.1.0 which is compatible with the new API.

In addition to the new Socket.io the API now also provides a REST API to check what's playing on SomaFM. The `track` events are more on-time. It automatically provides data for all radio stations available and it uses less bandwidth on SomaFM. And overall it should be more stable.
Check out http://api2.somascrobbler.com/ for documentation.

If April 1st if too early please write a commend and I can postpone the upgrade.

This issue will be closed after the upgrade.

**Comment by gyaresu** [comment]
That's an extremely polite heads up. Thanks Max.
I use the SomaPlayer and only had a play with your excellent codebase.

So I'm fine and thanks again.

**Comment by moneypenny** [comment]
https://github.com/moneypenny/soma-chrome has been updated to use 1.3.5 of socket io. Things seem to be working. I'm still using the api.somascrobbler.com server, which looks to be updated now.

**Comment by maxkueng** [comment]
Awesome! Yes, api.somascrobbler.com and api2.somascrobbler.com are now the same thing.
