### ISSUE TITLE
SSL-cert for api.somascrobbler.com is outdated

### ISSUE THREAD

**Issue by numbata** [maxkueng/somascrobbler-api#5]
Hi. I try to use Chrome plugin and got this error on fetch track info:  NET::ERR_CERT_DATE_INVALID.
Could you update SSL-cert, please?

**Comment by maxkueng** [comment]
Sorry it took so long to fix. There was a problem with my LetsEncrypt auto-renewal thing. API is up and running again.

**Comment by numbata** [comment]
@maxkueng Again :)

**Comment by maxkueng** [comment]
Thanks for reporting. I fixed it. There was something wrong with that automatic renewal of the LetsEncrypt SSl certificate.

**Comment by numbata** [comment]
@maxkueng `NET::ERR_CERT_DATE_INVALID` got today.

**Comment by maxkueng** [comment]
Fixed it. Thanks again.

Somehow the automatic renewal didn't work but I also didn't receive any emails from LetsEncrypt that the certificate was about to expire.

So I updated JrCs/docker-letsencrypt-nginx-proxy-companion but there's a bug JrCs/docker-letsencrypt-nginx-proxy-companion#130 so I currently have to use a workaround.
