### ISSUE TITLE
Failed to connect to api.somascrobbler.com port 443: Connection refused

### ISSUE THREAD

**Issue by numbata** [maxkueng/somascrobbler-api#6]
Hi, again.

Is it possible to bring back https://api.somascrobbler.com? How can i help you to do it (donate or something else)?

**Comment by maxkueng** [comment]
The API is back. It's not a money issue (its costs me less than a latte per month). I use [JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) to provide SSL and for some reason it failed to renew the SSL certificate and just restarting the containers didn't help either. So I had to upgrade the docker-letsencrypt-nginx-proxy-companion image and reset the machine and re-run the Ansible playbooks. Maybe there was a bug in the Nginx proxy companion.
